### ISSUE TITLE
Preserve namespace

### ISSUE THREAD

**Issue by iku000888** [owainlewis/yaml#23]
Hi, thanks for a useful tool!

Just throwing in an issue as I noticed that entries pre-fixed before a '/' does not round trip.

Example:

```yml
- wantedly/pretty-slack-notify@0.3.5:
        username:       ""
        channel:        "xxxx"
        webhook_url:    $SLACK_WEBHOOK_URL
        failed_message: "Build Failed :thinking_face:"
        notify_on:      "failed"
        branches:       ""
```

when I parse and re-render 
`wantedly/pretty-slack-notify@0.3.5: `
the result is `pretty-slack-notify@0.3.5: `
